josemarluedke/frontile

packages/docs/app/components/demo/forms/input-radio-group/standard/index.hbs
packages/docs/app/components/demo/forms/input-radio-group/standard/index.js
packages/docs/app/components/demo/forms/input-radio/standard/index.hbs
packages/docs/app/components/demo/forms/input-radio/standard/index.js
packages/docs/app/components/demo/forms/input-text/standard/index.hbs
packages/docs/app/router.js
packages/docs/app/templates/docs.hbs
packages/docs/app/templates/docs/forms/input-radio-group.md
packages/docs/app/templates/docs/forms/input-radio.md
packages/forms/addon/components/input-radio-group.hbs
packages/forms/addon/components/input-radio-group.ts
packages/forms/addon/components/input-radio.hbs
packages/forms/addon/components/input-radio.ts
packages/forms/app/components/input-radio-group.js
packages/forms/app/components/input-radio.js
packages/forms/tests/integration/components/input-radio-group-test.ts
packages/forms/tests/integration/components/input-radio-test.ts

Add InputRadio and InputRadioGroup component

---

packages/forms/addon/components/form-checkbox.hbs
packages/forms/addon/components/form-radio.hbs
packages/forms/addon/tailwind/default-options.js
packages/forms/addon/tailwind/index.js
packages/forms/tests/integration/components/form-checkbox-group-test.ts
packages/forms/tests/integration/components/form-checkbox-test.ts
packages/forms/tests/integration/components/form-radio-group-test.ts
packages/forms/tests/integration/components/form-radio-test.ts

Source: https://twitter.com/adamwathan/status/1217864323466432516

Fix styles on checkbox and radio inputs when label text wraps

---

packages/forms/addon/tailwind/default-options.js
packages/forms/addon/tailwind/index.js
packages/forms/package.json
yarn.lock

Add focus box-shadow to form inputs

---

packages/forms/addon/components/form-input.hbs
packages/forms/addon/components/form-textarea.hbs
packages/forms/addon/tailwind/default-options.js
packages/forms/tests/integration/components/form-input-test.ts
packages/forms/tests/integration/components/form-textarea-test.ts

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute

Refactor input to use aria-invalid instead of has-error class

---

packages/buttons/addon/tailwind/index.js

Fixes this problem with danger:

Add specificity for buttons with intent

---

.github/workflows/ci.yml

Hopefully, this will fix the issue of tag deployment.

Use actions/checkout@v2

---

packages/modals/.ember-cli
packages/modals/.npmignore
packages/modals/.watchmanconfig
packages/modals/LICENSE.md
packages/modals/README.md
packages/modals/addon/tailwind/default-options.js
packages/modals/config/ember-try.js
packages/modals/config/environment.js
packages/modals/ember-cli-build.js
packages/modals/index.js
packages/modals/package.json
packages/modals/tailwind.js
packages/modals/testem.js
packages/modals/tests/dummy/app/app.js
packages/modals/tests/dummy/app/config/environment.d.ts
packages/modals/tests/dummy/app/index.html
packages/modals/tests/dummy/app/router.js
packages/modals/tests/dummy/app/styles/app.css
packages/modals/tests/dummy/app/styles/tailwind.config.js
packages/modals/tests/dummy/app/templates/application.hbs
packages/modals/tests/dummy/config/environment.js
packages/modals/tests/dummy/config/optional-features.json
packages/modals/tests/dummy/config/targets.js
packages/modals/tests/dummy/public/robots.txt
packages/modals/tests/index.html
packages/modals/tests/test-helper.ts
packages/modals/tsconfig.json
packages/modals/types/global.d.ts
yarn.lock

This sets up the structure of the package, nothing in it yet.

Create @frontile/modals package

---

packages/buttons/addon/components/button.hbs
packages/buttons/addon/components/button.ts
packages/buttons/tailwind.js
packages/buttons/tests/integration/components/button-test.ts

Refactor button classes to use BEM naming

---

packages/notifications/addon/components/notification-card.hbs
packages/notifications/addon/components/notification-card.ts
packages/notifications/addon/components/notifications-container.hbs
packages/notifications/addon/components/notifications-container.ts
packages/notifications/addon/tailwind/default-options.js
packages/notifications/ember-cli-build.js
packages/notifications/tailwind.js
packages/notifications/tests/integration/components/notification-card-test.ts
packages/notifications/tests/integration/components/notifications-container-test.ts

Refactor Notifications package to use BEM CSS naming

---

.github/workflows/ci.yml

I just noticed with PR #77 that tests didn't run.

Run GitHub Actions on Pull-Request

---

packages/changeset-form/package.json

This addon doesn't play well if you have changeset in your app.

fix(changeset-form): more generous versioning for changeset

---

packages/core/addon/components/collapsible.hbs
packages/core/addon/components/collapsible.ts
packages/core/addon/utils/safe-styles.ts
packages/core/app/components/collapsible.js
packages/core/app/utils/safe-styles.js
packages/core/package.json
packages/core/tests/dummy/app/components/collapsible-demo.hbs
packages/core/tests/dummy/app/components/collapsible-demo.ts
packages/core/tests/dummy/app/templates/application.hbs
packages/core/tests/integration/components/collapsible-test.ts
packages/core/tests/unit/utils/safe-styles-test.ts
packages/docs/app/components/demo/core/collapsible/index.hbs
packages/docs/app/components/demo/core/collapsible/index.js
packages/docs/app/router.js
packages/docs/app/templates/docs.hbs
packages/docs/app/templates/docs/core/collapsible.md
yarn.lock

This is an unstyled component to be used to build higher-level components.

Create Collapsible component in core

---

packages/overlays/addon/components/drawer/index.hbs
packages/overlays/addon/components/modal/index.hbs

Pass focusTrapOptions arg to overlay from Modal and Drawer comps

---

packages/overlays/addon/components/overlay.ts

Consider Overlay isOpen as truty for backdrop

---

packages/docs/app/templates/docs/buttons/index.md
packages/docs/app/templates/docs/core/index.md
packages/docs/app/templates/docs/forms/index.md
packages/docs/app/templates/docs/notifications/index.md
packages/docs/app/templates/docs/overlays/index.md

As per https://github.com/FullHuman/purgecss/issues/439 whitelist was changed to safelist.
Fixes #129

fix: update purgecss documentation

---

packages/buttons/tailwind/default-options.js

But introduced in the TailwindCSS v2 upgrade.

Fix button outline due to TW v2 upgrade

---

.github/workflows/ci.yml
config/ember-try.js
package.json
packages/buttons/ember-cli-build.js
packages/buttons/package.json
packages/changeset-form/ember-cli-build.js
packages/changeset-form/package.json
packages/core/ember-cli-build.js
packages/core/package.json
packages/forms/addon/components/form-select.hbs
packages/forms/ember-cli-build.js
packages/forms/package.json
packages/notifications/ember-cli-build.js
packages/notifications/package.json
packages/overlays/ember-cli-build.js
packages/overlays/package.json
yarn.lock

This only set things up, it does not enable to run in CI yet.

Setup Embroider for testing in CI

---

site/app/config/tailwind.config.js

- Removed duplicated  buttons plugin import

Bug duplicated buttons plugin import in site tailwind config

---

site/app/router.js
site/app/templates/not-found.hbs

404 page not found

---

packages/buttons/package.json
packages/buttons/src/components/progress-bar.gts
packages/buttons/src/components/progress-bar.md
packages/buttons/src/index.ts
packages/buttons/src/template-registry.ts
packages/theme/src/components/index.ts
packages/theme/src/components/progress-bar.ts
packages/theme/src/plugin.ts
test-app/app/components/buttons/progress-bar.gts
test-app/app/templates/buttons.hbs
test-app/ember-cli-build.js
test-app/tailwind.config.js
test-app/tests/integration/components/buttons/progress-bar-test.ts

PR adds progress bar component and docs

Progress bar component

---

package.json
packages/buttons/package.json
packages/buttons/src/components/button.gts
packages/buttons/src/components/dropdown.gts
packages/buttons/src/components/dropdown.md
packages/buttons/src/components/listbox/item.gts
packages/buttons/src/components/listbox/listbox.gts
packages/buttons/src/index.ts
packages/buttons/src/template-registry.ts
packages/overlays/package.json
packages/overlays/src/-private/dom.js
packages/overlays/src/components/overlay.gts
packages/theme/src/components/dropdown.ts
packages/theme/src/components/index.ts
packages/theme/src/components/listbox.ts
packages/theme/src/components/overlays.ts
pnpm-lock.yaml
test-app/app/components/buttons/dropdown.gts
test-app/app/templates/buttons.hbs
test-app/tests/integration/components/buttons/dropdown-test.ts
test-app/tests/integration/components/overlays/drawer-test.ts
test-app/tests/integration/components/overlays/modal-test.ts
test-app/tests/integration/components/overlays/overlay-test.ts

feat: Add Dropdown component

---

packages/collections/src/components/dropdown.gts
packages/collections/src/components/listbox/listbox.gts
packages/collections/src/utils/listManager.ts
pnpm-lock.yaml
test-app/package.json
test-app/tests/integration/components/collections/listbox-test.ts
test-app/tests/integration/components/forms/select-test.ts

Several improvements to Listbox:
- Ability to auto activate first item in the list;
- Events to capture active item change;
- Ability to add events to an external element outside of the Listbox;
- This is useful for building search input on top of a Listbox.

feat: Listbox: auto activate first item; onActiveItemChange; events on element

---

packages/theme/src/components/index.ts
packages/theme/src/components/spinner.ts
packages/utilities/package.json
packages/utilities/src/components/spinner.gts
packages/utilities/src/components/spinner.md
packages/utilities/src/index.ts
packages/utilities/src/template-registry.ts
pnpm-lock.yaml
site/app/components/signature-data.ts
site/package.json
test-app/app/components/core/demo.hbs

feat: add Spinner component to utilities pkg

---

packages/theme/src/components/button.ts
packages/theme/src/components/close-button.ts

fix: focus-visable typo

---

packages/changeset-form/docs/changeset-form-usage.md

Fix a typo on the changeset form page

---

docs/customization/component-styles.md
docs/customization/theme.md

closes https://github.com/josemarluedke/frontile/issues/301

docs: add docs for customizing component styles

---

.claude/settings.local.json
site/app/components/docfy/docfy-sidebar-nav/content.gts
site/app/styles/app.css

- Redesign navigation to match hierarchical structure with collapsible sections
- Add expandable/collapsible functionality with arrow icons and smooth animations
- Implement auto-expansion of sections containing the current page on load
- Add auto-navigation to first page when expanding sections user hasn't visited
- Update spacing and typography to match cleaner, more compact design
- Add comprehensive dark mode support for all navigation elements
- Configure global typography hierarchy with softer text colors
- Update prose classes for better readability in light/dark modes
- Remove explicit color classes in favor of global typography inheritance

feat: redesign site navigation with collapsible sections and improved UX
