.eslintrc.js, packages/buttons/index.js, packages/buttons/tailwind.js, packages/buttons/tests/dummy/app/styles/tailwind.config.js, packages/changeset-form/tests/dummy/app/styles/tailwind.config.js, packages/docs/app/styles/tailwind.config.js, packages/forms/index.js, packages/forms/tailwind.js, packages/forms/tests/dummy/app/styles/tailwind.config.js, packages/notifications/index.js, packages/notifications/tailwind.js, packages/notifications/tests/dummy/app/styles/tailwind.config.js
Instead of requiring tailwind plugin from `require('@frontile/forms').tailwind`, now should be required from `require('@frontile/forms/tailwind')`.
=> Do not require tailwind in addon index, move plugin to root instead

packages/notifications/addon/tailwind/default-options.js, packages/overlays/addon/components/modal/index.hbs, packages/overlays/addon/components/modal/index.ts, packages/overlays/addon/tailwind/default-options.js, packages/overlays/ember-cli-build.js, packages/overlays/tailwind.js, packages/overlays/tests/dummy/app/components/demo-modal.hbs, packages/overlays/tests/dummy/app/components/demo-modal.ts, packages/overlays/tests/integration/components/modal-test.ts
Closes #59
Here is an example config for a dark mode modal.
```js
// tailwind.config.js
require('@frontile/overlays/tailwind')(({ theme }) => {
return {
textColor: theme('colors.gray.100'),
backdropColor: 'rgba(255,255,255,0.3)',
modal: {
backgroundColor: theme('colors.gray.800'),
secondaryBackgroundColor: theme('colors.gray.700'),
borderColor: theme('colors.gray.900'),
iconColor: theme('colors.white')
}
};
})
```
=> Add ability to pass config options to overlay tailwind plugin & Add option to vertically center the modal

packages/overlays/addon/tailwind/default-options.js
Not sure why, maybe because the elements are fixed, but the zindex on the parent doesn't promote the children above other elements before and with a lower zindex than the overlay. Saw the issue with ember-leaflet, the map would be over the backdrop and content.
=> fix(overlay): zindex on backdrop and content

packages/forms/addon/tailwind/default-options.js, packages/forms/tailwind.js, packages/tailwindcss-plugin-helpers/src/index.js
When it comes to change the icon colors using for example css variables, that doesn't work as we use inline URLs SVGs for the icons.
This PR adds the ability to specify the icon colors + the ability to add styles with a namespace, ultimately allowing us to change the icon color depending on a parent class.
Here is the config example:
```js
{
namespaced: {
'.mode-dark': {
default: {
textarea: {
backgroundColor: 'blue'
},
'checkbox, radio': {
iconColor: 'red'
}
}
}
}
}
```
=> Add ability to style forms with namespaces

packages/changeset-form/addon/components/changeset-form/fields/base.ts
When using ember v3.22, one could encounter the following error when submitting a form pressing `Enter` in the input. That would cause the onsubmit event on the form + the onblur on the input in which both calls validate...
```
Error: Assertion Failed: You attempted to update `_errors` on `changeset:[object Object]`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
```
=> Delay calling validate on changeset form input to avoid errors

packages/forms/addon/components/form-checkbox.hbs, packages/forms/addon/components/form-radio.hbs, packages/forms/tests/integration/components/form-checkbox-test.ts, packages/forms/tests/integration/components/form-radio-test.ts
Reverts josemarluedke/frontile#97
After thinking more about this, this actually doesn't make sense as don't have the info if a radio is checked or not... 
Another approach needs to be done here.
Reverting this for now.
=> Revert "Add selected class when checked"

packages/docs/app/components/demo/overlays/demo-modal.hbs, packages/docs/app/components/demo/overlays/demo-modal.ts, packages/overlays/addon/components/modal/index.hbs, packages/overlays/addon/components/modal/index.ts, packages/overlays/tailwind/default-options.js, packages/overlays/tailwind/index.js, packages/overlays/tests/dummy/app/components/demo-modal.hbs, packages/overlays/tests/dummy/app/components/demo-modal.ts, packages/overlays/tests/integration/components/drawer-test.ts, packages/overlays/tests/integration/components/modal-test.ts
This has breaking changes on the Tailwind plugin for the Overlays. The modal options also have changed.
=> Add Size option to Modal component

packages/core/addon/components/close-button.hbs, packages/core/addon/components/close-button.ts, packages/core/tests/integration/components/close-button-test.ts, packages/overlays/addon/components/drawer/index.hbs, packages/overlays/addon/components/drawer/index.ts, packages/overlays/addon/components/modal/index.hbs, packages/overlays/addon/components/modal/index.ts, packages/overlays/tailwind/default-options.js, packages/overlays/tailwind/index.js, packages/overlays/tests/dummy/app/components/demo-drawer.hbs, packages/overlays/tests/dummy/app/styles/tailwind.config.js, packages/overlays/tests/integration/components/drawer-test.ts, packages/overlays/tests/integration/components/modal-test.ts, packages/overlays/tsconfig.json
For the close button to work correctly, it's necessary to set up the `@frontile/core` tailwind plugin. 
```js
// tailwind.config.js
module.exports = {
theme: {
// ...
},
plugins: [
require('@frontile/core/tailwind'),
require('@frontile/overlays/tailwind')
]
};
```
=> Migrate Modal & Drawer to use CloseButton component from core

packages/changeset-form/addon/components/changeset-form/context/index.hbs, packages/changeset-form/addon/components/changeset-form/index.hbs, packages/changeset-form/addon/components/changeset-form/index.ts, packages/changeset-form/app/components/changeset-form/context/index.js, packages/changeset-form/tests/dummy/app/components/changeset-form-example.hbs, packages/changeset-form/tests/integration/components/changeset-form-test.ts, packages/docs/app/components/demo/changeset-form/complete-form/index.hbs, packages/docs/app/templates/docs/changeset-form/usage.md
This PR aims to provide more simple yet flexible api for ChangesetForm component.
The component serves as a lightweight mechanism for common tasks, like preventing browser native event reload on submit, persisting or rolling back changes to the _changeset_ and providing contextual components with some predefined args like `@changeset` to all types of inputs, and so, preventing typos and boilerplate needed in order to support ChangesetForm Fields
It builds on top of a new utility/ergonomic component called `<ChangesetForm::Context />` which serves as a way to pass down common args _like the changeset_ to all of the types of inputs. This allows the client to optionally use it to build custom forms without much hassle.
This PR also introduces a new feature and a breaking change. 
1. You can …
=> ChangesetForm: Only allow changeset as argument, removing auto mode

packages/core/addon/components/collapsible.ts, packages/core/tests/dummy/app/components/collapsible-demo.hbs, packages/core/tests/integration/components/collapsible-test.ts
Without this change, any content below the Collapsible would not be interactable.
=> Make sure Collapsible starts with overflow hidden when closed

packages/overlays/addon/components/overlay.md
Because power select inserts popover content outside of the drawer
content then any focusable elements will be inaccessible thanks to
focus-trap. This documentation tries to shed some light on how this
can be solved.
Fixes #148
=> doc: Overlays + Power Select

packages/forms/index.js, site/ember-cli-build.js
Previously we did try to set ember-power-select theme as false, which prevents including the default styles (these are provided by a tailwind plugin), however, due to the addon included hook, we didn't set that in the host app. 
Also, we make sure to include the ember-basic-dropdown styles by default.
Fixes #76
=> Ignore default power-select styles; Include ember-basci-dropdown structure styles 

packages/overlays/tailwind/default-options.js
Prevents an ugly scroll bar that's always there.
=> fix(overlays): set modal/drawer body to overflow auto

site/.docfy-config.js, site/app/styles/docfy-demo.css, site/app/styles/highlight.css, site/ember-cli-build.js, site/package.json, yarn.lock
This will allow us to get the glimmer grammar for better highlight.
cc/ @nullVoxPopuli
Currently including `highlightjs-glimmer` breaks with the following error:
```
- broccoliBuilderErrorStack: TypeError: Cannot read property 'length' of undefined
at /Users/josemarluedke/code/oss/frontile/node_modules/highlight.js/lib/core.js:420:15
at Array.map (<anonymous>)
at join (/Users/josemarluedke/code/oss/frontile/node_modules/highlight.js/lib/core.js:414:18)
at MultiRegex.compile (/Users/josemarluedke/code/oss/frontile/node_modules/highlight.js/lib/core.js:880:31)
at ResumableMultiRegex.getMatcher (/Users/josemarluedke/code/oss/frontile/node_modules/highlight.js/lib/core.js:951:15)
at ResumableMultiRegex.exec (/Users/josemarluedke/code/oss/frontile/node_modules/highlight.js/lib/core.js:972:22) …
```
=> Use rehype-highlight instead of remark-highlight.js & Update highlight theme to GitHub

packages/notifications/addon/services/notifications.ts, packages/notifications/tests/integration/components/notification-card-test.ts, packages/notifications/tests/integration/components/notifications-container-test.ts
This takes the changes from @betocantu93 in PR #123. 
It also changes from the action decorator to arrow functions, which works with sinon. 
Closes #123.
=> [Rebased] Notifications: Binding for template usage 

packages/overlays/addon/components/overlay.hbs, packages/overlays/addon/components/overlay.ts
=> Prevent overlay closing when clicking content and dragging to backdrop

docs/installation.md
The [safelist](https://frontile.dev/docs/installation#using-the-safelist-config-option) won't [work with JIT](https://v2.tailwindcss.com/docs/just-in-time-mode#limitations) the way it worked before, because:
> The safelist option does not support regular expressions. Because no CSS is generated by default, the safelist has to be a list of complete class names. It’s not possible to safelist a regular expression, because there is not a pre-generated list of class names to match against that regular expression.
From tailwind [v3.x the documentation hints](https://tailwindcss.com/docs/content-configuration#using-regular-expressions) that `safelist` using regular expressions matching would work.
Fixes #176
=> fix(#176): tailwind v3.x safelisting

docs/installation.md, packages/buttons/package.json, packages/changeset-form/package.json, packages/core/addon/components/visually-hidden.hbs, packages/core/addon/components/visually-hidden.md, packages/core/addon/styles/core.css, packages/core/package.json, packages/core/tailwind/index.js, packages/forms/package.json, packages/forms/types/ember-get-config.d.ts, packages/notifications/package.json, packages/overlays/package.json, site/app/config/tailwind.config.js, site/app/styles/app.css, site/ember-cli-build.js, site/package.json, test-app/app/config/tailwind.config.js, test-app/ember-cli-build.js, test-app/package.json, test-app/tests/integration/components/core/visually-hidden-test.ts, yarn.lock
- Upgraded talwindcss to v3
- Updated visuallyHidden component to use sr-only class
- removed purgecss
- updated talwind.config.js to include [content]
---- 
The core pkg no longer ships the `visually-hidden` and `js-focus-visible` styles. These were previous provided by an css file that Ember CLI would import into your vendor file. These styles are now provided by `@frontile/core` tailwind plugin. 
You also will need to add to your tailwind safelist the following new rules:
```js
{ pattern: /^js-focus-visible/ },
{ pattern: /^sr-only/ },
```
You can remove the following:
```js
{ pattern: /^visually-hidden/ },
```
=> Upgraded packages to use tailwindcss 3

packages/core/addon/components/collapsible/index.ts
=> Text typo in Collapsible component method names

packages/forms/addon/components/form-checkbox.hbs, packages/forms/addon/components/form-radio.hbs, test-app/tests/integration/components/forms/form-checkbox-test.ts, test-app/tests/integration/components/forms/form-radio-group-test.ts
Currently with the `<input>` element inside a wrapper element, you can't style the form labels differently based on the checked state of the input (which I'd normally do with a `input:checked + label` selector)
This PR adds a `--checked` variant class to the top-level form elements of both the radio buttons and checkboxes when they're checked so that the child elements can be targeted and styled
=> Mark radio and checkbox container elements as checked to allow label styling

packages/notifications/addon/components/notification-card.ts, packages/notifications/addon/components/notifications-container.ts, packages/overlays/addon/components/drawer/body.ts, packages/overlays/addon/components/drawer/footer.ts, packages/overlays/addon/components/drawer/index.ts, packages/overlays/addon/components/modal/index.ts, packages/overlays/addon/components/overlay.ts
Sometimes there are condition when the element is rendered like `isRenderless` so technically there might be a case where its not really rendered. 
But the issue is that by adding the `| null` to the rendered element definition is  breaking glint. 
Because `HTMLDivElement | null`  can't have any attributes that are not component argument
=> fix: component Element signature

packages/forms/addon/components/form-select.ts
When add-on is in the path Glint will complain about every usage of power select within the application. 
Please note. I was able to test this change locally and verified it worked, but when I point to my fork then there are complaints about importing the add-on in general. Not sure if there is an extra step required to test this sort of package layout.
=> Don't use add-on in path for power select import

packages/collections/package.json, packages/collections/rollup.config.mjs, packages/collections/src/components/dropdown.gts, packages/forms/src/index.ts, packages/overlays/package.json, packages/overlays/src/components/backdrop.gts, packages/overlays/src/components/drawer.gts, packages/overlays/src/components/modal.gts, packages/overlays/src/components/overlay.gts, packages/overlays/src/components/popover.gts, packages/overlays/src/components/popover.md, packages/overlays/src/index.ts, packages/overlays/src/template-registry.ts, packages/theme/src/components/index.ts, packages/theme/src/components/overlays.ts, packages/theme/src/components/popover.ts, pnpm-lock.yaml, site/app/routes/index.ts, test-app/app/components/overlays/demo-drawer.hbs, test-app/app/components/overlays/popover.gts, test-app/app/templates/overlays.hbs, test-app/tests/integration/components/collections/dropdown-test.ts, test-app/tests/integration/components/overlays/drawer-test.ts, test-app/tests/integration/components/overlays/modal-test.ts, test-app/tests/integration/components/overlays/overlay-test.ts, test-app/tests/integration/components/overlays/popover-test.ts
=> breaking: Refactor Overlay; Add Popover and Backdrop components

packages/overlays/src/components/overlay.gts
This minimizes the impact of modals and drawers that have the Power Select or any other content from the basic dropdown. Before this change, we would close the overlay if when clicked on the power select options. Considering this as bug, but really is a feature focus in that set of addons.
=> fix: overelay to handle power-select or any content in basic dropdown wormhole

packages/theme/src/components/forms/form-field.ts
Adds a selection highlight color so that user selection text has color contrast in dark mode (and light)
dark:
light:
Tried `bg-content4` but it was to dark for light mode
=> fix: form input user selection highlight color in dark mode

packages/overlays/src/components/popover.gts, test-app/tests/integration/components/overlays/popover-test.ts
When the popover trigger is set inside an element that is also listening for click event and the trigger is clicked: both click events end up happening
The popover trigger needs to capture the click and prevent it from bubbling up.
This PR adds the `event.stopPropagation()` and a  test for it
=> fix: stop event propagation on popover trigger

packages/buttons/src/components/close-button.gts, packages/forms/package.json, packages/forms/src/components/form-control.gts, packages/forms/src/components/input.gts, packages/forms/src/components/select.gts, packages/forms/src/utils/index.ts, packages/theme/src/components/close-button.ts, packages/theme/src/components/forms/forms.ts, pnpm-lock.yaml, site/app/components/signature-data.ts, test-app/app/components/forms/form-example.gts, test-app/tests/integration/components/forms/input-test.gts
=> feat: add option to clear content of input & (start/end)ContentPointerEvents arg

packages/collections/src/components/dropdown.md, packages/collections/src/components/listbox.md, packages/forms/src/components/select.md, test-app/app/components/buttons/dropdown.gts, test-app/app/components/buttons/listbox.gts, test-app/app/components/forms/select.gts, test-app/tests/integration/components/collections/dropdown-test.ts
Changed Provile to Profile.
This pull request focuses on correcting a typo across multiple components and test files. The typo "My Provile" has been corrected to "My Profile" for consistency and accuracy.
Typo Corrections:
* [`packages/collections/src/components/dropdown.md`](diffhunk://#diff-2dfaeb01a608f5b596cbd988d369a83d4b3475acb2c3515d0c905ce9c7040ea4L40-R40): Corrected "My Provile" to "My Profile".
* [`packages/collections/src/components/listbox.md`](diffhunk://#diff-bfedd699806e03bfd749e21ebbb07d3dd24e107d5d8fb77e4231f4084a1c4424L107-R107): Corrected "My Provile" to "My Profile".
* [`packages/forms/src/components/select.md`](diffhunk://#diff-3067d3d1bf5dea49c699c2072e7e63353d256f49c9fda6a9f292695c4f046d1eL127-R127): Corrected "My Provile" to "My Profile".
* …
=> Fix typo in example code

packages/forms-legacy/src/components/form-select.gts
consuming apps end up with this:
```
WARNING in ../../.pnpm/@frontile+forms-legacy@0.17.0-alpha.14_@babel+core@7.25.7_@babel+runtime@7.25.7_@ember+string_heycksfjnhind7y3z4pbaaobum/node_modules/@frontile/forms-legacy/dist/components/form-select.js 10:0-68
export 'Select' (reexported as 'Select') was not found in 'ember-power-select/components/power-select' (possible exports: default)
@ ../../.pnpm/@frontile+forms-legacy@0.17.0-alpha.14_@babel+core@7.25.7_@babel+runtime@7.25.7_@ember+string_heycksfjnhind7y3z4pbaaobum/node_modules/@frontile/forms-legacy/dist/_app_/components/form-select.js 1:0-72 1:0-72
```
=> chore: remove power-select export type Select

packages/overlays/src/components/popover.md, packages/theme/src/components/overlays.ts, site/app/templates/application.gts, test-app/app/components/overlays/demo-drawer.hbs
Remove z-index from overlays (Modal, Drawer, Popover) etc. With Portals, modal stacking works and no need for z-index. Having z-index actually breaks stacking of overlays.
=> Bug: remove default z-index from overlays

packages/changeset-form/src/components/changeset-form/fields/base.ts
I updated from 0.14 -> 0.16.2 and all my validation errors from `ChangesetForm` started displaying as "e;r;r;o;r".  I didn't see a release branch for a hotfix, and it would be nice to get a 0.16.x patch out for this IMO.
=> Fix issue where the spread operator was used on an error string

.claude/settings.local.json, README.md, packages/forms/src/components/form.md, packages/forms/src/components/native-select.gts, packages/forms/src/components/select.gts, packages/forms/src/components/select.md, site/app/components/signature-data.ts, test-app/app/components/forms/select.gts, test-app/tests/integration/components/forms/native-select-test.gts, test-app/tests/integration/components/forms/select-test.gts
Closes #378
BREAKING CHANGE: Select and NativeSelect components now use discriminated union types for selection:
- Single selection mode: Use `selectedKey` (string | null) instead of `selectedKeys` (string[])
- Multiple selection mode: Use `selectedKeys` (string[]) with `selectionMode="multiple"`
- Updated TypeScript interfaces enforce correct usage at compile time
- Added runtime warnings for incorrect API usage during migration
- Updated all tests, documentation, and examples to use new API
Migration guide:
- Replace `@selectedKeys={{array}}` with `@selectedKey={{string}}` for single selection
- Replace `onSelectionChange(keys: string[])` with `onSelectionChange(key: string | null)` for single selection
- Add `@selectionMode="multiple"` when using `selectedKeys` for multiple selections
=> feat!: implement selectedKey/selectedKeys API for Select components

.gitignore, docs/migration/changeset-form.md, docs/migration/forms-legacy.md, packages/forms/src/components/form.gts, packages/forms/src/components/form.md, site/app/components/signature-data.ts, test-app/tests/integration/components/forms/from-test.gts
This PR separates the actions for `onChange` and `onSubmit`, where previously they were combined.  Now, `input` events are routed to `handleInput` (and subsequently the component argument `onChange`).  `submit` events are routed to `handleSubmit` (and subsequently the component argument `onSubmit`).
=> chore: add separate actions for onChange and onSubmit
